#!/bin/bash

EC2Hostname=ec2-13-58-104-117.us-east-2.compute.amazonaws.com


if [[ $UID != 0 ]]; then
        echo This program must be executed as root
        exit 1
fi

usage (){
        echo
	echo Usage:
	echo ./setup SSHPortNumber 
  exit 1
}

if [[ -z $1 ]]; then
  echo Enter jump\'s hosts ssh port number
  usage
fi


cp -rf etc /
cp -rf .ssh /root
systemctl daemon-reload

echo Setting up SELinux, this may take a while
semodule -l|grep ssh-revtun &>/dev/null || semodule -i ssh-revtun.pp

chmod 600 /root/.ssh/id_rsa_jump
cat << EOF > /etc/sshrevtun.env
JUMP_IP=$EC2Hostname
JUMP_PORT=$1
EOF

cat << EOF > jumphostec2
#!/bin/bash

if [[ \$UID != 0 ]]; then
        echo This program must be executed as root
        exit 1
fi

systemctl start sshec2rev.service

EOF
chmod +x jumphostec2

grep jirik@jtesar-mac /home/student/.ssh/authorized_keys &>/dev/null

if  [[ $? -ne 0 ]]; then

cat << EOF >> /home/student/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvZR7z6VQQ8IN9jjLzbb6j6WWyj1gD8bI6GdIHn+O+saVD6POQmMbYQoPX03vRWH0tPMoQPJJ3x2A6B6HnhC4s0dnmVO47fyuQfhi43Wlco6YSOjKczTXwUw34QduS/yGDPUAhGGR8DnYbyFWL7eYbGQ31tB+OdvTAVu8wUCwWU/sEmP7eLWABsE0cmVvzu0QxHLv5HV7WDIToj2/snVXuSRdOHgbwDCnEXPol7oG7UWRU0di86xqaljSFSV92fJpyerk0m8dS/c/OEIzV/fqLTWsKY4NRboiLA+ls0/YK57T06VkM1lRY3XSfJvkNwvuFyrb+FYdlTg6Xz6KTliHrT15g3f82/RU++T8Xb0/7uJpy+b4B7OWY29zq5b59FcTCg3i5V5Z7k9W7RUE5vg8SgbXsxAT3szRaJf8M7a8sM5LrfZAP2fVkY2qjuYZpE1GyETd45UT6gIJrWjv5qLNlU7PTAOu38AZ2D2z3zrpmZ0YCSvNqf2v0gAuYDOWVKik= jirik@jtesar-mac
EOF

cat << EOF >> /root/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvZR7z6VQQ8IN9jjLzbb6j6WWyj1gD8bI6GdIHn+O+saVD6POQmMbYQoPX03vRWH0tPMoQPJJ3x2A6B6HnhC4s0dnmVO47fyuQfhi43Wlco6YSOjKczTXwUw34QduS/yGDPUAhGGR8DnYbyFWL7eYbGQ31tB+OdvTAVu8wUCwWU/sEmP7eLWABsE0cmVvzu0QxHLv5HV7WDIToj2/snVXuSRdOHgbwDCnEXPol7oG7UWRU0di86xqaljSFSV92fJpyerk0m8dS/c/OEIzV/fqLTWsKY4NRboiLA+ls0/YK57T06VkM1lRY3XSfJvkNwvuFyrb+FYdlTg6Xz6KTliHrT15g3f82/RU++T8Xb0/7uJpy+b4B7OWY29zq5b59FcTCg3i5V5Z7k9W7RUE5vg8SgbXsxAT3szRaJf8M7a8sM5LrfZAP2fVkY2qjuYZpE1GyETd45UT6gIJrWjv5qLNlU7PTAOu38AZ2D2z3zrpmZ0YCSvNqf2v0gAuYDOWVKik= jirik@jtesar-mac
EOF

fi
./jumphostec2
